#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("query_address0", 9, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("query_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("query_q0", 16, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("query_address1", 9, hls_out, 0, "ap_memory", "MemPortADDR2", 1),
	Port_Property("query_ce1", 1, hls_out, 0, "ap_memory", "MemPortCE2", 1),
	Port_Property("query_q1", 16, hls_in, 0, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("key_address0", 9, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("key_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("key_q0", 16, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("key_address1", 9, hls_out, 1, "ap_memory", "MemPortADDR2", 1),
	Port_Property("key_ce1", 1, hls_out, 1, "ap_memory", "MemPortCE2", 1),
	Port_Property("key_q1", 16, hls_in, 1, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("value_r_address0", 8, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("value_r_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("value_r_q0", 16, hls_in, 2, "ap_memory", "mem_dout", 1),
	Port_Property("value_r_address1", 8, hls_out, 2, "ap_memory", "MemPortADDR2", 1),
	Port_Property("value_r_ce1", 1, hls_out, 2, "ap_memory", "MemPortCE2", 1),
	Port_Property("value_r_q1", 16, hls_in, 2, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("padding_mask_address0", 4, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("padding_mask_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("padding_mask_q0", 16, hls_in, 3, "ap_memory", "mem_dout", 1),
	Port_Property("padding_mask_address1", 4, hls_out, 3, "ap_memory", "MemPortADDR2", 1),
	Port_Property("padding_mask_ce1", 1, hls_out, 3, "ap_memory", "MemPortCE2", 1),
	Port_Property("padding_mask_q1", 16, hls_in, 3, "ap_memory", "MemPortDOUT2", 1),
	Port_Property("layer5_out_address0", 8, hls_out, 4, "ap_memory", "mem_address", 1),
	Port_Property("layer5_out_ce0", 1, hls_out, 4, "ap_memory", "mem_ce", 1),
	Port_Property("layer5_out_we0", 1, hls_out, 4, "ap_memory", "mem_we", 1),
	Port_Property("layer5_out_d0", 16, hls_out, 4, "ap_memory", "mem_din", 1),
	Port_Property("layer5_out_address1", 8, hls_out, 4, "ap_memory", "MemPortADDR2", 1),
	Port_Property("layer5_out_ce1", 1, hls_out, 4, "ap_memory", "MemPortCE2", 1),
	Port_Property("layer5_out_we1", 1, hls_out, 4, "ap_memory", "MemPortWE2", 1),
	Port_Property("layer5_out_d1", 16, hls_out, 4, "ap_memory", "MemPortDIN2", 1),
};
const char* HLS_Design_Meta::dut_name = "myproject";
