// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_merge_sort_ap_fixed_16_6_5_3_0_config5_Pipeline_VITIS_LOOP_161_58 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        temp_221,
        temp_220,
        temp_219,
        temp_218,
        temp_217,
        temp_216,
        temp_215,
        temp_214,
        zext_ln161_1,
        k_27,
        mux_case_0301203,
        mux_case_1302207,
        mux_case_2303211,
        mux_case_3304215,
        mux_case_4305219,
        mux_case_5306223,
        mux_case_6307227,
        mux_case_7308231,
        temp_238_out,
        temp_238_out_ap_vld,
        temp_237_out,
        temp_237_out_ap_vld,
        temp_236_out,
        temp_236_out_ap_vld,
        temp_235_out,
        temp_235_out_ap_vld,
        temp_234_out,
        temp_234_out_ap_vld,
        temp_233_out,
        temp_233_out_ap_vld,
        temp_232_out,
        temp_232_out_ap_vld,
        temp_231_out,
        temp_231_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] temp_221;
input  [31:0] temp_220;
input  [31:0] temp_219;
input  [31:0] temp_218;
input  [31:0] temp_217;
input  [31:0] temp_216;
input  [31:0] temp_215;
input  [31:0] temp_214;
input  [2:0] zext_ln161_1;
input  [31:0] k_27;
input  [31:0] mux_case_0301203;
input  [31:0] mux_case_1302207;
input  [31:0] mux_case_2303211;
input  [31:0] mux_case_3304215;
input  [31:0] mux_case_4305219;
input  [31:0] mux_case_5306223;
input  [31:0] mux_case_6307227;
input  [31:0] mux_case_7308231;
output  [31:0] temp_238_out;
output   temp_238_out_ap_vld;
output  [31:0] temp_237_out;
output   temp_237_out_ap_vld;
output  [31:0] temp_236_out;
output   temp_236_out_ap_vld;
output  [31:0] temp_235_out;
output   temp_235_out_ap_vld;
output  [31:0] temp_234_out;
output   temp_234_out_ap_vld;
output  [31:0] temp_233_out;
output   temp_233_out_ap_vld;
output  [31:0] temp_232_out;
output   temp_232_out_ap_vld;
output  [31:0] temp_231_out;
output   temp_231_out_ap_vld;

reg ap_idle;
reg temp_238_out_ap_vld;
reg temp_237_out_ap_vld;
reg temp_236_out_ap_vld;
reg temp_235_out_ap_vld;
reg temp_234_out_ap_vld;
reg temp_233_out_ap_vld;
reg temp_232_out_ap_vld;
reg temp_231_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_359_p3;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] k_fu_98;
wire   [31:0] k_1_fu_416_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [3:0] j_fu_102;
wire   [3:0] add_ln163_fu_378_p2;
wire   [3:0] zext_ln161_1_cast_fu_302_p1;
reg   [31:0] temp_fu_106;
wire   [31:0] temp_8_fu_384_p19;
wire   [2:0] trunc_ln147_1_fu_374_p1;
reg   [31:0] temp_1_fu_110;
reg   [31:0] temp_2_fu_114;
reg   [31:0] temp_3_fu_118;
reg   [31:0] temp_4_fu_122;
reg   [31:0] temp_5_fu_126;
reg   [31:0] temp_6_fu_130;
reg   [31:0] temp_7_fu_134;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] temp_8_fu_384_p17;
wire   [2:0] temp_8_fu_384_p18;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_282;
reg    ap_condition_285;
reg    ap_condition_288;
reg    ap_condition_291;
reg    ap_condition_294;
reg    ap_condition_297;
reg    ap_condition_300;
reg    ap_condition_303;
wire   [2:0] temp_8_fu_384_p1;
wire   [2:0] temp_8_fu_384_p3;
wire   [2:0] temp_8_fu_384_p5;
wire   [2:0] temp_8_fu_384_p7;
wire  signed [2:0] temp_8_fu_384_p9;
wire  signed [2:0] temp_8_fu_384_p11;
wire  signed [2:0] temp_8_fu_384_p13;
wire  signed [2:0] temp_8_fu_384_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 k_fu_98 = 32'd0;
#0 j_fu_102 = 4'd0;
#0 temp_fu_106 = 32'd0;
#0 temp_1_fu_110 = 32'd0;
#0 temp_2_fu_114 = 32'd0;
#0 temp_3_fu_118 = 32'd0;
#0 temp_4_fu_122 = 32'd0;
#0 temp_5_fu_126 = 32'd0;
#0 temp_6_fu_130 = 32'd0;
#0 temp_7_fu_134 = 32'd0;
#0 ap_done_reg = 1'b0;
end

myproject_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U1141(
    .din0(mux_case_0301203),
    .din1(mux_case_1302207),
    .din2(mux_case_2303211),
    .din3(mux_case_3304215),
    .din4(mux_case_4305219),
    .din5(mux_case_5306223),
    .din6(mux_case_6307227),
    .din7(mux_case_7308231),
    .def(temp_8_fu_384_p17),
    .sel(temp_8_fu_384_p18),
    .dout(temp_8_fu_384_p19)
);

myproject_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_102 <= zext_ln161_1_cast_fu_302_p1;
        end else if (((tmp_fu_359_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            j_fu_102 <= add_ln163_fu_378_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_98 <= k_27;
        end else if (((tmp_fu_359_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            k_fu_98 <= k_1_fu_416_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_1_fu_110 <= temp_215;
        end else if ((1'b1 == ap_condition_282)) begin
            temp_1_fu_110 <= temp_8_fu_384_p19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_2_fu_114 <= temp_216;
        end else if ((1'b1 == ap_condition_285)) begin
            temp_2_fu_114 <= temp_8_fu_384_p19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_3_fu_118 <= temp_217;
        end else if ((1'b1 == ap_condition_288)) begin
            temp_3_fu_118 <= temp_8_fu_384_p19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_4_fu_122 <= temp_218;
        end else if ((1'b1 == ap_condition_291)) begin
            temp_4_fu_122 <= temp_8_fu_384_p19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_5_fu_126 <= temp_219;
        end else if ((1'b1 == ap_condition_294)) begin
            temp_5_fu_126 <= temp_8_fu_384_p19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_6_fu_130 <= temp_220;
        end else if ((1'b1 == ap_condition_297)) begin
            temp_6_fu_130 <= temp_8_fu_384_p19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_7_fu_134 <= temp_221;
        end else if ((1'b1 == ap_condition_300)) begin
            temp_7_fu_134 <= temp_8_fu_384_p19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_fu_106 <= temp_214;
        end else if ((1'b1 == ap_condition_303)) begin
            temp_fu_106 <= temp_8_fu_384_p19;
        end
    end
end

always @ (*) begin
    if (((tmp_fu_359_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_359_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_231_out_ap_vld = 1'b1;
    end else begin
        temp_231_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_359_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_232_out_ap_vld = 1'b1;
    end else begin
        temp_232_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_359_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_233_out_ap_vld = 1'b1;
    end else begin
        temp_233_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_359_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_234_out_ap_vld = 1'b1;
    end else begin
        temp_234_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_359_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_235_out_ap_vld = 1'b1;
    end else begin
        temp_235_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_359_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_236_out_ap_vld = 1'b1;
    end else begin
        temp_236_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_359_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_237_out_ap_vld = 1'b1;
    end else begin
        temp_237_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_359_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_238_out_ap_vld = 1'b1;
    end else begin
        temp_238_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln163_fu_378_p2 = (j_fu_102 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_282 = ((tmp_fu_359_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_1_fu_374_p1 == 3'd1));
end

always @ (*) begin
    ap_condition_285 = ((tmp_fu_359_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_1_fu_374_p1 == 3'd2));
end

always @ (*) begin
    ap_condition_288 = ((tmp_fu_359_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_1_fu_374_p1 == 3'd3));
end

always @ (*) begin
    ap_condition_291 = ((tmp_fu_359_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_1_fu_374_p1 == 3'd4));
end

always @ (*) begin
    ap_condition_294 = ((tmp_fu_359_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_1_fu_374_p1 == 3'd5));
end

always @ (*) begin
    ap_condition_297 = ((tmp_fu_359_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_1_fu_374_p1 == 3'd6));
end

always @ (*) begin
    ap_condition_300 = ((tmp_fu_359_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_1_fu_374_p1 == 3'd7));
end

always @ (*) begin
    ap_condition_303 = ((tmp_fu_359_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_1_fu_374_p1 == 3'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign k_1_fu_416_p2 = (k_fu_98 + 32'd1);

assign temp_231_out = temp_fu_106;

assign temp_232_out = temp_1_fu_110;

assign temp_233_out = temp_2_fu_114;

assign temp_234_out = temp_3_fu_118;

assign temp_235_out = temp_4_fu_122;

assign temp_236_out = temp_5_fu_126;

assign temp_237_out = temp_6_fu_130;

assign temp_238_out = temp_7_fu_134;

assign temp_8_fu_384_p17 = 'bx;

assign temp_8_fu_384_p18 = j_fu_102[2:0];

assign tmp_fu_359_p3 = j_fu_102[32'd3];

assign trunc_ln147_1_fu_374_p1 = k_fu_98[2:0];

assign zext_ln161_1_cast_fu_302_p1 = zext_ln161_1;

endmodule //myproject_merge_sort_ap_fixed_16_6_5_3_0_config5_Pipeline_VITIS_LOOP_161_58
