// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_13_4_4_0_0_ap_fixed_13_4_4_0_0_config5_dense_1 (
        ap_clk,
        ap_rst,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        weights_4_val,
        weights_5_val,
        weights_6_val,
        weights_7_val,
        idx,
        ap_return_0,
        ap_return_1,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [12:0] data_4_val;
input  [12:0] data_5_val;
input  [12:0] data_6_val;
input  [12:0] data_7_val;
input  [12:0] weights_4_val;
input  [12:0] weights_5_val;
input  [12:0] weights_6_val;
input  [12:0] weights_7_val;
input  [2:0] idx;
output  [12:0] ap_return_0;
output  [12:0] ap_return_1;
input   ap_ce;

wire   [12:0] add_ln42_fu_320_p2;
reg   [12:0] add_ln42_reg_1473;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] and_ln42_274_fu_444_p2;
reg   [0:0] and_ln42_274_reg_1478;
wire   [0:0] or_ln42_112_fu_474_p2;
reg   [0:0] or_ln42_112_reg_1483;
wire   [12:0] add_ln42_31_fu_553_p2;
reg   [12:0] add_ln42_31_reg_1488;
wire   [0:0] and_ln42_281_fu_677_p2;
reg   [0:0] and_ln42_281_reg_1493;
wire   [0:0] or_ln42_115_fu_707_p2;
reg   [0:0] or_ln42_115_reg_1498;
wire   [12:0] add_ln42_32_fu_812_p2;
reg   [12:0] add_ln42_32_reg_1503;
wire   [0:0] and_ln42_288_fu_936_p2;
reg   [0:0] and_ln42_288_reg_1508;
wire   [0:0] or_ln42_118_fu_966_p2;
reg   [0:0] or_ln42_118_reg_1513;
wire   [12:0] add_ln42_33_fu_1045_p2;
reg   [12:0] add_ln42_33_reg_1518;
wire   [0:0] and_ln42_295_fu_1169_p2;
reg   [0:0] and_ln42_295_reg_1523;
wire   [0:0] or_ln42_121_fu_1199_p2;
reg   [0:0] or_ln42_121_reg_1528;
wire  signed [12:0] mul_ln73_32_fu_144_p0;
wire  signed [25:0] sext_ln73_53_fu_733_p1;
wire    ap_block_pp0_stage0;
wire  signed [12:0] mul_ln73_fu_145_p0;
wire  signed [25:0] sext_ln73_fu_241_p1;
wire  signed [12:0] mul_ln73_33_fu_146_p0;
wire  signed [12:0] mul_ln73_31_fu_147_p0;
wire   [12:0] a_fu_221_p7;
wire   [12:0] a_fu_221_p9;
wire   [25:0] mul_ln73_fu_145_p2;
wire   [7:0] trunc_ln42_fu_286_p1;
wire   [0:0] tmp_2837_fu_270_p3;
wire   [0:0] icmp_ln42_fu_290_p2;
wire   [0:0] or_ln42_fu_304_p2;
wire   [0:0] tmp_2838_fu_278_p3;
wire   [0:0] and_ln42_fu_310_p2;
wire   [12:0] trunc_ln_fu_260_p4;
wire   [12:0] zext_ln42_fu_316_p1;
wire   [0:0] tmp_2840_fu_326_p3;
wire   [0:0] tmp_2839_fu_296_p3;
wire   [0:0] xor_ln42_fu_334_p2;
wire   [2:0] tmp_8_fu_346_p4;
wire   [3:0] tmp_s_fu_362_p4;
wire   [0:0] and_ln42_271_fu_340_p2;
wire   [0:0] icmp_ln42_152_fu_372_p2;
wire   [0:0] icmp_ln42_153_fu_378_p2;
wire   [0:0] tmp_2841_fu_392_p3;
wire   [0:0] icmp_ln42_151_fu_356_p2;
wire   [0:0] xor_ln42_166_fu_400_p2;
wire   [0:0] and_ln42_272_fu_406_p2;
wire   [0:0] select_ln42_fu_384_p3;
wire   [0:0] xor_ln42_151_fu_426_p2;
wire   [0:0] tmp_fu_252_p3;
wire   [0:0] or_ln42_111_fu_432_p2;
wire   [0:0] xor_ln42_152_fu_438_p2;
wire   [0:0] select_ln42_151_fu_412_p3;
wire   [0:0] and_ln42_273_fu_420_p2;
wire   [0:0] and_ln42_275_fu_450_p2;
wire   [0:0] or_ln42_122_fu_456_p2;
wire   [0:0] xor_ln42_153_fu_462_p2;
wire   [0:0] and_ln42_276_fu_468_p2;
wire   [25:0] mul_ln73_31_fu_147_p2;
wire   [7:0] trunc_ln42_34_fu_519_p1;
wire   [0:0] tmp_2843_fu_503_p3;
wire   [0:0] icmp_ln42_154_fu_523_p2;
wire   [0:0] or_ln42_113_fu_537_p2;
wire   [0:0] tmp_2844_fu_511_p3;
wire   [0:0] and_ln42_277_fu_543_p2;
wire   [12:0] trunc_ln42_s_fu_493_p4;
wire   [12:0] zext_ln42_31_fu_549_p1;
wire   [0:0] tmp_2846_fu_559_p3;
wire   [0:0] tmp_2845_fu_529_p3;
wire   [0:0] xor_ln42_154_fu_567_p2;
wire   [2:0] tmp_1056_fu_579_p4;
wire   [3:0] tmp_1057_fu_595_p4;
wire   [0:0] and_ln42_278_fu_573_p2;
wire   [0:0] icmp_ln42_156_fu_605_p2;
wire   [0:0] icmp_ln42_157_fu_611_p2;
wire   [0:0] tmp_2847_fu_625_p3;
wire   [0:0] icmp_ln42_155_fu_589_p2;
wire   [0:0] xor_ln42_167_fu_633_p2;
wire   [0:0] and_ln42_279_fu_639_p2;
wire   [0:0] select_ln42_154_fu_617_p3;
wire   [0:0] xor_ln42_155_fu_659_p2;
wire   [0:0] tmp_2842_fu_485_p3;
wire   [0:0] or_ln42_114_fu_665_p2;
wire   [0:0] xor_ln42_156_fu_671_p2;
wire   [0:0] select_ln42_155_fu_645_p3;
wire   [0:0] and_ln42_280_fu_653_p2;
wire   [0:0] and_ln42_282_fu_683_p2;
wire   [0:0] or_ln42_123_fu_689_p2;
wire   [0:0] xor_ln42_157_fu_695_p2;
wire   [0:0] and_ln42_283_fu_701_p2;
wire   [12:0] a_11_fu_713_p7;
wire   [12:0] a_11_fu_713_p9;
wire   [25:0] mul_ln73_32_fu_144_p2;
wire   [7:0] trunc_ln42_35_fu_778_p1;
wire   [0:0] tmp_2849_fu_762_p3;
wire   [0:0] icmp_ln42_158_fu_782_p2;
wire   [0:0] or_ln42_116_fu_796_p2;
wire   [0:0] tmp_2850_fu_770_p3;
wire   [0:0] and_ln42_284_fu_802_p2;
wire   [12:0] trunc_ln42_15_fu_752_p4;
wire   [12:0] zext_ln42_32_fu_808_p1;
wire   [0:0] tmp_2852_fu_818_p3;
wire   [0:0] tmp_2851_fu_788_p3;
wire   [0:0] xor_ln42_158_fu_826_p2;
wire   [2:0] tmp_1058_fu_838_p4;
wire   [3:0] tmp_1059_fu_854_p4;
wire   [0:0] and_ln42_285_fu_832_p2;
wire   [0:0] icmp_ln42_160_fu_864_p2;
wire   [0:0] icmp_ln42_161_fu_870_p2;
wire   [0:0] tmp_2853_fu_884_p3;
wire   [0:0] icmp_ln42_159_fu_848_p2;
wire   [0:0] xor_ln42_168_fu_892_p2;
wire   [0:0] and_ln42_286_fu_898_p2;
wire   [0:0] select_ln42_158_fu_876_p3;
wire   [0:0] xor_ln42_159_fu_918_p2;
wire   [0:0] tmp_2848_fu_744_p3;
wire   [0:0] or_ln42_117_fu_924_p2;
wire   [0:0] xor_ln42_160_fu_930_p2;
wire   [0:0] select_ln42_159_fu_904_p3;
wire   [0:0] and_ln42_287_fu_912_p2;
wire   [0:0] and_ln42_289_fu_942_p2;
wire   [0:0] or_ln42_124_fu_948_p2;
wire   [0:0] xor_ln42_161_fu_954_p2;
wire   [0:0] and_ln42_290_fu_960_p2;
wire   [25:0] mul_ln73_33_fu_146_p2;
wire   [7:0] trunc_ln42_36_fu_1011_p1;
wire   [0:0] tmp_2855_fu_995_p3;
wire   [0:0] icmp_ln42_162_fu_1015_p2;
wire   [0:0] or_ln42_119_fu_1029_p2;
wire   [0:0] tmp_2856_fu_1003_p3;
wire   [0:0] and_ln42_291_fu_1035_p2;
wire   [12:0] trunc_ln42_16_fu_985_p4;
wire   [12:0] zext_ln42_33_fu_1041_p1;
wire   [0:0] tmp_2858_fu_1051_p3;
wire   [0:0] tmp_2857_fu_1021_p3;
wire   [0:0] xor_ln42_162_fu_1059_p2;
wire   [2:0] tmp_1060_fu_1071_p4;
wire   [3:0] tmp_1061_fu_1087_p4;
wire   [0:0] and_ln42_292_fu_1065_p2;
wire   [0:0] icmp_ln42_164_fu_1097_p2;
wire   [0:0] icmp_ln42_165_fu_1103_p2;
wire   [0:0] tmp_2859_fu_1117_p3;
wire   [0:0] icmp_ln42_163_fu_1081_p2;
wire   [0:0] xor_ln42_169_fu_1125_p2;
wire   [0:0] and_ln42_293_fu_1131_p2;
wire   [0:0] select_ln42_162_fu_1109_p3;
wire   [0:0] xor_ln42_163_fu_1151_p2;
wire   [0:0] tmp_2854_fu_977_p3;
wire   [0:0] or_ln42_120_fu_1157_p2;
wire   [0:0] xor_ln42_164_fu_1163_p2;
wire   [0:0] select_ln42_163_fu_1137_p3;
wire   [0:0] and_ln42_294_fu_1145_p2;
wire   [0:0] and_ln42_296_fu_1175_p2;
wire   [0:0] or_ln42_125_fu_1181_p2;
wire   [0:0] xor_ln42_165_fu_1187_p2;
wire   [0:0] and_ln42_297_fu_1193_p2;
wire   [12:0] select_ln42_152_fu_1205_p3;
wire   [12:0] select_ln42_156_fu_1218_p3;
wire   [12:0] select_ln42_160_fu_1231_p3;
wire   [12:0] select_ln42_164_fu_1244_p3;
wire  signed [12:0] select_ln42_153_fu_1212_p3;
wire  signed [12:0] select_ln42_161_fu_1238_p3;
wire  signed [13:0] sext_ln58_31_fu_1261_p1;
wire  signed [13:0] sext_ln58_fu_1257_p1;
wire   [13:0] add_ln58_fu_1271_p2;
wire   [12:0] add_ln58_22_fu_1265_p2;
wire   [0:0] tmp_2860_fu_1277_p3;
wire   [0:0] tmp_2861_fu_1285_p3;
wire   [0:0] xor_ln58_fu_1293_p2;
wire   [0:0] xor_ln58_71_fu_1305_p2;
wire   [0:0] xor_ln58_72_fu_1317_p2;
wire   [0:0] and_ln58_fu_1299_p2;
wire   [0:0] xor_ln58_73_fu_1323_p2;
wire   [0:0] and_ln58_31_fu_1311_p2;
wire   [0:0] or_ln58_fu_1329_p2;
wire   [12:0] select_ln58_fu_1335_p3;
wire   [12:0] select_ln58_51_fu_1343_p3;
wire  signed [12:0] select_ln42_157_fu_1225_p3;
wire  signed [12:0] select_ln42_165_fu_1251_p3;
wire  signed [13:0] sext_ln58_33_fu_1363_p1;
wire  signed [13:0] sext_ln58_32_fu_1359_p1;
wire   [13:0] add_ln58_11_fu_1373_p2;
wire   [12:0] add_ln58_23_fu_1367_p2;
wire   [0:0] tmp_2862_fu_1379_p3;
wire   [0:0] tmp_2863_fu_1387_p3;
wire   [0:0] xor_ln58_74_fu_1395_p2;
wire   [0:0] xor_ln58_75_fu_1407_p2;
wire   [0:0] xor_ln58_76_fu_1419_p2;
wire   [0:0] and_ln58_32_fu_1401_p2;
wire   [0:0] xor_ln58_77_fu_1425_p2;
wire   [0:0] and_ln58_33_fu_1413_p2;
wire   [0:0] or_ln58_11_fu_1431_p2;
wire   [12:0] select_ln58_53_fu_1437_p3;
wire   [12:0] select_ln58_54_fu_1445_p3;
wire   [12:0] select_ln58_52_fu_1351_p3;
wire   [12:0] select_ln58_55_fu_1453_p3;
wire  signed [2:0] a_fu_221_p1;
wire  signed [2:0] a_fu_221_p3;
wire  signed [2:0] a_fu_221_p5;
wire  signed [2:0] a_11_fu_713_p1;
wire  signed [2:0] a_11_fu_713_p3;
wire  signed [2:0] a_11_fu_713_p5;
wire    ap_ce_reg;

myproject_mul_13s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_13s_13s_26_1_1_U747(
    .din0(mul_ln73_32_fu_144_p0),
    .din1(weights_6_val),
    .dout(mul_ln73_32_fu_144_p2)
);

myproject_mul_13s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_13s_13s_26_1_1_U748(
    .din0(mul_ln73_fu_145_p0),
    .din1(weights_4_val),
    .dout(mul_ln73_fu_145_p2)
);

myproject_mul_13s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_13s_13s_26_1_1_U749(
    .din0(mul_ln73_33_fu_146_p0),
    .din1(weights_7_val),
    .dout(mul_ln73_33_fu_146_p2)
);

myproject_mul_13s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_13s_13s_26_1_1_U750(
    .din0(mul_ln73_31_fu_147_p0),
    .din1(weights_5_val),
    .dout(mul_ln73_31_fu_147_p2)
);

myproject_sparsemux_7_3_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 13 ),
    .CASE1( 3'h5 ),
    .din1_WIDTH( 13 ),
    .CASE2( 3'h6 ),
    .din2_WIDTH( 13 ),
    .def_WIDTH( 13 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 13 ))
sparsemux_7_3_13_1_1_U751(
    .din0(data_4_val),
    .din1(data_5_val),
    .din2(data_6_val),
    .def(a_fu_221_p7),
    .sel(idx),
    .dout(a_fu_221_p9)
);

myproject_sparsemux_7_3_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h4 ),
    .din0_WIDTH( 13 ),
    .CASE1( 3'h5 ),
    .din1_WIDTH( 13 ),
    .CASE2( 3'h6 ),
    .din2_WIDTH( 13 ),
    .def_WIDTH( 13 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 13 ))
sparsemux_7_3_13_1_1_U752(
    .din0(data_5_val),
    .din1(data_6_val),
    .din2(data_7_val),
    .def(a_11_fu_713_p7),
    .sel(idx),
    .dout(a_11_fu_713_p9)
);

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        add_ln42_31_reg_1488 <= add_ln42_31_fu_553_p2;
        add_ln42_32_reg_1503 <= add_ln42_32_fu_812_p2;
        add_ln42_33_reg_1518 <= add_ln42_33_fu_1045_p2;
        add_ln42_reg_1473 <= add_ln42_fu_320_p2;
        and_ln42_274_reg_1478 <= and_ln42_274_fu_444_p2;
        and_ln42_281_reg_1493 <= and_ln42_281_fu_677_p2;
        and_ln42_288_reg_1508 <= and_ln42_288_fu_936_p2;
        and_ln42_295_reg_1523 <= and_ln42_295_fu_1169_p2;
        or_ln42_112_reg_1483 <= or_ln42_112_fu_474_p2;
        or_ln42_115_reg_1498 <= or_ln42_115_fu_707_p2;
        or_ln42_118_reg_1513 <= or_ln42_118_fu_966_p2;
        or_ln42_121_reg_1528 <= or_ln42_121_fu_1199_p2;
    end
end

assign a_11_fu_713_p7 = 'bx;

assign a_fu_221_p7 = 'bx;

assign add_ln42_31_fu_553_p2 = (trunc_ln42_s_fu_493_p4 + zext_ln42_31_fu_549_p1);

assign add_ln42_32_fu_812_p2 = (trunc_ln42_15_fu_752_p4 + zext_ln42_32_fu_808_p1);

assign add_ln42_33_fu_1045_p2 = (trunc_ln42_16_fu_985_p4 + zext_ln42_33_fu_1041_p1);

assign add_ln42_fu_320_p2 = (trunc_ln_fu_260_p4 + zext_ln42_fu_316_p1);

assign add_ln58_11_fu_1373_p2 = ($signed(sext_ln58_33_fu_1363_p1) + $signed(sext_ln58_32_fu_1359_p1));

assign add_ln58_22_fu_1265_p2 = ($signed(select_ln42_161_fu_1238_p3) + $signed(select_ln42_153_fu_1212_p3));

assign add_ln58_23_fu_1367_p2 = ($signed(select_ln42_165_fu_1251_p3) + $signed(select_ln42_157_fu_1225_p3));

assign add_ln58_fu_1271_p2 = ($signed(sext_ln58_31_fu_1261_p1) + $signed(sext_ln58_fu_1257_p1));

assign and_ln42_271_fu_340_p2 = (xor_ln42_fu_334_p2 & tmp_2839_fu_296_p3);

assign and_ln42_272_fu_406_p2 = (xor_ln42_166_fu_400_p2 & icmp_ln42_151_fu_356_p2);

assign and_ln42_273_fu_420_p2 = (icmp_ln42_152_fu_372_p2 & and_ln42_271_fu_340_p2);

assign and_ln42_274_fu_444_p2 = (xor_ln42_152_fu_438_p2 & or_ln42_111_fu_432_p2);

assign and_ln42_275_fu_450_p2 = (tmp_2840_fu_326_p3 & select_ln42_151_fu_412_p3);

assign and_ln42_276_fu_468_p2 = (xor_ln42_153_fu_462_p2 & tmp_fu_252_p3);

assign and_ln42_277_fu_543_p2 = (tmp_2844_fu_511_p3 & or_ln42_113_fu_537_p2);

assign and_ln42_278_fu_573_p2 = (xor_ln42_154_fu_567_p2 & tmp_2845_fu_529_p3);

assign and_ln42_279_fu_639_p2 = (xor_ln42_167_fu_633_p2 & icmp_ln42_155_fu_589_p2);

assign and_ln42_280_fu_653_p2 = (icmp_ln42_156_fu_605_p2 & and_ln42_278_fu_573_p2);

assign and_ln42_281_fu_677_p2 = (xor_ln42_156_fu_671_p2 & or_ln42_114_fu_665_p2);

assign and_ln42_282_fu_683_p2 = (tmp_2846_fu_559_p3 & select_ln42_155_fu_645_p3);

assign and_ln42_283_fu_701_p2 = (xor_ln42_157_fu_695_p2 & tmp_2842_fu_485_p3);

assign and_ln42_284_fu_802_p2 = (tmp_2850_fu_770_p3 & or_ln42_116_fu_796_p2);

assign and_ln42_285_fu_832_p2 = (xor_ln42_158_fu_826_p2 & tmp_2851_fu_788_p3);

assign and_ln42_286_fu_898_p2 = (xor_ln42_168_fu_892_p2 & icmp_ln42_159_fu_848_p2);

assign and_ln42_287_fu_912_p2 = (icmp_ln42_160_fu_864_p2 & and_ln42_285_fu_832_p2);

assign and_ln42_288_fu_936_p2 = (xor_ln42_160_fu_930_p2 & or_ln42_117_fu_924_p2);

assign and_ln42_289_fu_942_p2 = (tmp_2852_fu_818_p3 & select_ln42_159_fu_904_p3);

assign and_ln42_290_fu_960_p2 = (xor_ln42_161_fu_954_p2 & tmp_2848_fu_744_p3);

assign and_ln42_291_fu_1035_p2 = (tmp_2856_fu_1003_p3 & or_ln42_119_fu_1029_p2);

assign and_ln42_292_fu_1065_p2 = (xor_ln42_162_fu_1059_p2 & tmp_2857_fu_1021_p3);

assign and_ln42_293_fu_1131_p2 = (xor_ln42_169_fu_1125_p2 & icmp_ln42_163_fu_1081_p2);

assign and_ln42_294_fu_1145_p2 = (icmp_ln42_164_fu_1097_p2 & and_ln42_292_fu_1065_p2);

assign and_ln42_295_fu_1169_p2 = (xor_ln42_164_fu_1163_p2 & or_ln42_120_fu_1157_p2);

assign and_ln42_296_fu_1175_p2 = (tmp_2858_fu_1051_p3 & select_ln42_163_fu_1137_p3);

assign and_ln42_297_fu_1193_p2 = (xor_ln42_165_fu_1187_p2 & tmp_2854_fu_977_p3);

assign and_ln42_fu_310_p2 = (tmp_2838_fu_278_p3 & or_ln42_fu_304_p2);

assign and_ln58_31_fu_1311_p2 = (xor_ln58_71_fu_1305_p2 & tmp_2860_fu_1277_p3);

assign and_ln58_32_fu_1401_p2 = (xor_ln58_74_fu_1395_p2 & tmp_2863_fu_1387_p3);

assign and_ln58_33_fu_1413_p2 = (xor_ln58_75_fu_1407_p2 & tmp_2862_fu_1379_p3);

assign and_ln58_fu_1299_p2 = (xor_ln58_fu_1293_p2 & tmp_2861_fu_1285_p3);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return_0 = select_ln58_52_fu_1351_p3;

assign ap_return_1 = select_ln58_55_fu_1453_p3;

assign icmp_ln42_151_fu_356_p2 = ((tmp_8_fu_346_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln42_152_fu_372_p2 = ((tmp_s_fu_362_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln42_153_fu_378_p2 = ((tmp_s_fu_362_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_154_fu_523_p2 = ((trunc_ln42_34_fu_519_p1 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_155_fu_589_p2 = ((tmp_1056_fu_579_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln42_156_fu_605_p2 = ((tmp_1057_fu_595_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln42_157_fu_611_p2 = ((tmp_1057_fu_595_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_158_fu_782_p2 = ((trunc_ln42_35_fu_778_p1 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_159_fu_848_p2 = ((tmp_1058_fu_838_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln42_160_fu_864_p2 = ((tmp_1059_fu_854_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln42_161_fu_870_p2 = ((tmp_1059_fu_854_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_162_fu_1015_p2 = ((trunc_ln42_36_fu_1011_p1 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_163_fu_1081_p2 = ((tmp_1060_fu_1071_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln42_164_fu_1097_p2 = ((tmp_1061_fu_1087_p4 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln42_165_fu_1103_p2 = ((tmp_1061_fu_1087_p4 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_290_p2 = ((trunc_ln42_fu_286_p1 != 8'd0) ? 1'b1 : 1'b0);

assign mul_ln73_31_fu_147_p0 = sext_ln73_fu_241_p1;

assign mul_ln73_32_fu_144_p0 = sext_ln73_53_fu_733_p1;

assign mul_ln73_33_fu_146_p0 = sext_ln73_53_fu_733_p1;

assign mul_ln73_fu_145_p0 = sext_ln73_fu_241_p1;

assign or_ln42_111_fu_432_p2 = (xor_ln42_151_fu_426_p2 | tmp_2840_fu_326_p3);

assign or_ln42_112_fu_474_p2 = (and_ln42_276_fu_468_p2 | and_ln42_274_fu_444_p2);

assign or_ln42_113_fu_537_p2 = (tmp_2843_fu_503_p3 | icmp_ln42_154_fu_523_p2);

assign or_ln42_114_fu_665_p2 = (xor_ln42_155_fu_659_p2 | tmp_2846_fu_559_p3);

assign or_ln42_115_fu_707_p2 = (and_ln42_283_fu_701_p2 | and_ln42_281_fu_677_p2);

assign or_ln42_116_fu_796_p2 = (tmp_2849_fu_762_p3 | icmp_ln42_158_fu_782_p2);

assign or_ln42_117_fu_924_p2 = (xor_ln42_159_fu_918_p2 | tmp_2852_fu_818_p3);

assign or_ln42_118_fu_966_p2 = (and_ln42_290_fu_960_p2 | and_ln42_288_fu_936_p2);

assign or_ln42_119_fu_1029_p2 = (tmp_2855_fu_995_p3 | icmp_ln42_162_fu_1015_p2);

assign or_ln42_120_fu_1157_p2 = (xor_ln42_163_fu_1151_p2 | tmp_2858_fu_1051_p3);

assign or_ln42_121_fu_1199_p2 = (and_ln42_297_fu_1193_p2 | and_ln42_295_fu_1169_p2);

assign or_ln42_122_fu_456_p2 = (and_ln42_275_fu_450_p2 | and_ln42_273_fu_420_p2);

assign or_ln42_123_fu_689_p2 = (and_ln42_282_fu_683_p2 | and_ln42_280_fu_653_p2);

assign or_ln42_124_fu_948_p2 = (and_ln42_289_fu_942_p2 | and_ln42_287_fu_912_p2);

assign or_ln42_125_fu_1181_p2 = (and_ln42_296_fu_1175_p2 | and_ln42_294_fu_1145_p2);

assign or_ln42_fu_304_p2 = (tmp_2837_fu_270_p3 | icmp_ln42_fu_290_p2);

assign or_ln58_11_fu_1431_p2 = (xor_ln58_77_fu_1425_p2 | and_ln58_32_fu_1401_p2);

assign or_ln58_fu_1329_p2 = (xor_ln58_73_fu_1323_p2 | and_ln58_fu_1299_p2);

assign select_ln42_151_fu_412_p3 = ((and_ln42_271_fu_340_p2[0:0] == 1'b1) ? and_ln42_272_fu_406_p2 : icmp_ln42_152_fu_372_p2);

assign select_ln42_152_fu_1205_p3 = ((and_ln42_274_reg_1478[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign select_ln42_153_fu_1212_p3 = ((or_ln42_112_reg_1483[0:0] == 1'b1) ? select_ln42_152_fu_1205_p3 : add_ln42_reg_1473);

assign select_ln42_154_fu_617_p3 = ((and_ln42_278_fu_573_p2[0:0] == 1'b1) ? icmp_ln42_156_fu_605_p2 : icmp_ln42_157_fu_611_p2);

assign select_ln42_155_fu_645_p3 = ((and_ln42_278_fu_573_p2[0:0] == 1'b1) ? and_ln42_279_fu_639_p2 : icmp_ln42_156_fu_605_p2);

assign select_ln42_156_fu_1218_p3 = ((and_ln42_281_reg_1493[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign select_ln42_157_fu_1225_p3 = ((or_ln42_115_reg_1498[0:0] == 1'b1) ? select_ln42_156_fu_1218_p3 : add_ln42_31_reg_1488);

assign select_ln42_158_fu_876_p3 = ((and_ln42_285_fu_832_p2[0:0] == 1'b1) ? icmp_ln42_160_fu_864_p2 : icmp_ln42_161_fu_870_p2);

assign select_ln42_159_fu_904_p3 = ((and_ln42_285_fu_832_p2[0:0] == 1'b1) ? and_ln42_286_fu_898_p2 : icmp_ln42_160_fu_864_p2);

assign select_ln42_160_fu_1231_p3 = ((and_ln42_288_reg_1508[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign select_ln42_161_fu_1238_p3 = ((or_ln42_118_reg_1513[0:0] == 1'b1) ? select_ln42_160_fu_1231_p3 : add_ln42_32_reg_1503);

assign select_ln42_162_fu_1109_p3 = ((and_ln42_292_fu_1065_p2[0:0] == 1'b1) ? icmp_ln42_164_fu_1097_p2 : icmp_ln42_165_fu_1103_p2);

assign select_ln42_163_fu_1137_p3 = ((and_ln42_292_fu_1065_p2[0:0] == 1'b1) ? and_ln42_293_fu_1131_p2 : icmp_ln42_164_fu_1097_p2);

assign select_ln42_164_fu_1244_p3 = ((and_ln42_295_reg_1523[0:0] == 1'b1) ? 13'd4095 : 13'd4096);

assign select_ln42_165_fu_1251_p3 = ((or_ln42_121_reg_1528[0:0] == 1'b1) ? select_ln42_164_fu_1244_p3 : add_ln42_33_reg_1518);

assign select_ln42_fu_384_p3 = ((and_ln42_271_fu_340_p2[0:0] == 1'b1) ? icmp_ln42_152_fu_372_p2 : icmp_ln42_153_fu_378_p2);

assign select_ln58_51_fu_1343_p3 = ((and_ln58_31_fu_1311_p2[0:0] == 1'b1) ? 13'd4096 : add_ln58_22_fu_1265_p2);

assign select_ln58_52_fu_1351_p3 = ((or_ln58_fu_1329_p2[0:0] == 1'b1) ? select_ln58_fu_1335_p3 : select_ln58_51_fu_1343_p3);

assign select_ln58_53_fu_1437_p3 = ((xor_ln58_76_fu_1419_p2[0:0] == 1'b1) ? 13'd4095 : add_ln58_23_fu_1367_p2);

assign select_ln58_54_fu_1445_p3 = ((and_ln58_33_fu_1413_p2[0:0] == 1'b1) ? 13'd4096 : add_ln58_23_fu_1367_p2);

assign select_ln58_55_fu_1453_p3 = ((or_ln58_11_fu_1431_p2[0:0] == 1'b1) ? select_ln58_53_fu_1437_p3 : select_ln58_54_fu_1445_p3);

assign select_ln58_fu_1335_p3 = ((xor_ln58_72_fu_1317_p2[0:0] == 1'b1) ? 13'd4095 : add_ln58_22_fu_1265_p2);

assign sext_ln58_31_fu_1261_p1 = select_ln42_161_fu_1238_p3;

assign sext_ln58_32_fu_1359_p1 = select_ln42_157_fu_1225_p3;

assign sext_ln58_33_fu_1363_p1 = select_ln42_165_fu_1251_p3;

assign sext_ln58_fu_1257_p1 = select_ln42_153_fu_1212_p3;

assign sext_ln73_53_fu_733_p1 = $signed(a_11_fu_713_p9);

assign sext_ln73_fu_241_p1 = $signed(a_fu_221_p9);

assign tmp_1056_fu_579_p4 = {{mul_ln73_31_fu_147_p2[25:23]}};

assign tmp_1057_fu_595_p4 = {{mul_ln73_31_fu_147_p2[25:22]}};

assign tmp_1058_fu_838_p4 = {{mul_ln73_32_fu_144_p2[25:23]}};

assign tmp_1059_fu_854_p4 = {{mul_ln73_32_fu_144_p2[25:22]}};

assign tmp_1060_fu_1071_p4 = {{mul_ln73_33_fu_146_p2[25:23]}};

assign tmp_1061_fu_1087_p4 = {{mul_ln73_33_fu_146_p2[25:22]}};

assign tmp_2837_fu_270_p3 = mul_ln73_fu_145_p2[32'd9];

assign tmp_2838_fu_278_p3 = mul_ln73_fu_145_p2[32'd8];

assign tmp_2839_fu_296_p3 = mul_ln73_fu_145_p2[32'd21];

assign tmp_2840_fu_326_p3 = add_ln42_fu_320_p2[32'd12];

assign tmp_2841_fu_392_p3 = mul_ln73_fu_145_p2[32'd22];

assign tmp_2842_fu_485_p3 = mul_ln73_31_fu_147_p2[32'd25];

assign tmp_2843_fu_503_p3 = mul_ln73_31_fu_147_p2[32'd9];

assign tmp_2844_fu_511_p3 = mul_ln73_31_fu_147_p2[32'd8];

assign tmp_2845_fu_529_p3 = mul_ln73_31_fu_147_p2[32'd21];

assign tmp_2846_fu_559_p3 = add_ln42_31_fu_553_p2[32'd12];

assign tmp_2847_fu_625_p3 = mul_ln73_31_fu_147_p2[32'd22];

assign tmp_2848_fu_744_p3 = mul_ln73_32_fu_144_p2[32'd25];

assign tmp_2849_fu_762_p3 = mul_ln73_32_fu_144_p2[32'd9];

assign tmp_2850_fu_770_p3 = mul_ln73_32_fu_144_p2[32'd8];

assign tmp_2851_fu_788_p3 = mul_ln73_32_fu_144_p2[32'd21];

assign tmp_2852_fu_818_p3 = add_ln42_32_fu_812_p2[32'd12];

assign tmp_2853_fu_884_p3 = mul_ln73_32_fu_144_p2[32'd22];

assign tmp_2854_fu_977_p3 = mul_ln73_33_fu_146_p2[32'd25];

assign tmp_2855_fu_995_p3 = mul_ln73_33_fu_146_p2[32'd9];

assign tmp_2856_fu_1003_p3 = mul_ln73_33_fu_146_p2[32'd8];

assign tmp_2857_fu_1021_p3 = mul_ln73_33_fu_146_p2[32'd21];

assign tmp_2858_fu_1051_p3 = add_ln42_33_fu_1045_p2[32'd12];

assign tmp_2859_fu_1117_p3 = mul_ln73_33_fu_146_p2[32'd22];

assign tmp_2860_fu_1277_p3 = add_ln58_fu_1271_p2[32'd13];

assign tmp_2861_fu_1285_p3 = add_ln58_22_fu_1265_p2[32'd12];

assign tmp_2862_fu_1379_p3 = add_ln58_11_fu_1373_p2[32'd13];

assign tmp_2863_fu_1387_p3 = add_ln58_23_fu_1367_p2[32'd12];

assign tmp_8_fu_346_p4 = {{mul_ln73_fu_145_p2[25:23]}};

assign tmp_fu_252_p3 = mul_ln73_fu_145_p2[32'd25];

assign tmp_s_fu_362_p4 = {{mul_ln73_fu_145_p2[25:22]}};

assign trunc_ln42_15_fu_752_p4 = {{mul_ln73_32_fu_144_p2[21:9]}};

assign trunc_ln42_16_fu_985_p4 = {{mul_ln73_33_fu_146_p2[21:9]}};

assign trunc_ln42_34_fu_519_p1 = mul_ln73_31_fu_147_p2[7:0];

assign trunc_ln42_35_fu_778_p1 = mul_ln73_32_fu_144_p2[7:0];

assign trunc_ln42_36_fu_1011_p1 = mul_ln73_33_fu_146_p2[7:0];

assign trunc_ln42_fu_286_p1 = mul_ln73_fu_145_p2[7:0];

assign trunc_ln42_s_fu_493_p4 = {{mul_ln73_31_fu_147_p2[21:9]}};

assign trunc_ln_fu_260_p4 = {{mul_ln73_fu_145_p2[21:9]}};

assign xor_ln42_151_fu_426_p2 = (select_ln42_fu_384_p3 ^ 1'd1);

assign xor_ln42_152_fu_438_p2 = (tmp_fu_252_p3 ^ 1'd1);

assign xor_ln42_153_fu_462_p2 = (or_ln42_122_fu_456_p2 ^ 1'd1);

assign xor_ln42_154_fu_567_p2 = (tmp_2846_fu_559_p3 ^ 1'd1);

assign xor_ln42_155_fu_659_p2 = (select_ln42_154_fu_617_p3 ^ 1'd1);

assign xor_ln42_156_fu_671_p2 = (tmp_2842_fu_485_p3 ^ 1'd1);

assign xor_ln42_157_fu_695_p2 = (or_ln42_123_fu_689_p2 ^ 1'd1);

assign xor_ln42_158_fu_826_p2 = (tmp_2852_fu_818_p3 ^ 1'd1);

assign xor_ln42_159_fu_918_p2 = (select_ln42_158_fu_876_p3 ^ 1'd1);

assign xor_ln42_160_fu_930_p2 = (tmp_2848_fu_744_p3 ^ 1'd1);

assign xor_ln42_161_fu_954_p2 = (or_ln42_124_fu_948_p2 ^ 1'd1);

assign xor_ln42_162_fu_1059_p2 = (tmp_2858_fu_1051_p3 ^ 1'd1);

assign xor_ln42_163_fu_1151_p2 = (select_ln42_162_fu_1109_p3 ^ 1'd1);

assign xor_ln42_164_fu_1163_p2 = (tmp_2854_fu_977_p3 ^ 1'd1);

assign xor_ln42_165_fu_1187_p2 = (or_ln42_125_fu_1181_p2 ^ 1'd1);

assign xor_ln42_166_fu_400_p2 = (tmp_2841_fu_392_p3 ^ 1'd1);

assign xor_ln42_167_fu_633_p2 = (tmp_2847_fu_625_p3 ^ 1'd1);

assign xor_ln42_168_fu_892_p2 = (tmp_2853_fu_884_p3 ^ 1'd1);

assign xor_ln42_169_fu_1125_p2 = (tmp_2859_fu_1117_p3 ^ 1'd1);

assign xor_ln42_fu_334_p2 = (tmp_2840_fu_326_p3 ^ 1'd1);

assign xor_ln58_71_fu_1305_p2 = (tmp_2861_fu_1285_p3 ^ 1'd1);

assign xor_ln58_72_fu_1317_p2 = (tmp_2861_fu_1285_p3 ^ tmp_2860_fu_1277_p3);

assign xor_ln58_73_fu_1323_p2 = (xor_ln58_72_fu_1317_p2 ^ 1'd1);

assign xor_ln58_74_fu_1395_p2 = (tmp_2862_fu_1379_p3 ^ 1'd1);

assign xor_ln58_75_fu_1407_p2 = (tmp_2863_fu_1387_p3 ^ 1'd1);

assign xor_ln58_76_fu_1419_p2 = (tmp_2863_fu_1387_p3 ^ tmp_2862_fu_1379_p3);

assign xor_ln58_77_fu_1425_p2 = (xor_ln58_76_fu_1419_p2 ^ 1'd1);

assign xor_ln58_fu_1293_p2 = (tmp_2860_fu_1277_p3 ^ 1'd1);

assign zext_ln42_31_fu_549_p1 = and_ln42_277_fu_543_p2;

assign zext_ln42_32_fu_808_p1 = and_ln42_284_fu_802_p2;

assign zext_ln42_33_fu_1041_p1 = and_ln42_291_fu_1035_p2;

assign zext_ln42_fu_316_p1 = and_ln42_fu_310_p2;

endmodule //myproject_dense_latency_ap_fixed_13_4_4_0_0_ap_fixed_13_4_4_0_0_config5_dense_1
