Backend: Vivado
ClockPeriod: 5
ClockUncertainty: 12.5%
HLSConfig:
  LayerName:
    hept:
      Precision:
        accum: ap_fixed<16,4,AP_RND_CONV,AP_SAT>
        exp_table: ap_ufixed<16,0>
        result: ap_fixed<16,4,AP_RND_CONV,AP_SAT>
      ReuseFactor: 1
      Trace: false
    key:
      Precision:
        result: ap_fixed<16,4,AP_RND_CONV,AP_SAT>
      Trace: false
    query:
      Precision:
        result: ap_fixed<16,4,AP_RND_CONV,AP_SAT>
      Trace: false
  Model:
    BramFactor: 1000000000
    ChannelsLastConversion: 'off'
    Precision:
      default: ap_fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
    TransposeOutputs: false
IOType: io_parallel
InputData: /home/rian/A3D3/hept_model/hls4ml/data/hept_simplified_in.dat
InputShape:
- !!python/tuple
  - 5
  - 3
  - 2
  - 7
- !!python/tuple
  - 5
  - 3
  - 2
  - 7
OutputDir: /home/rian/A3D3/hept_model/hls4ml/hls4ml_projects/hept_simplified_kernel
OutputPredictions: /home/rian/A3D3/hept_model/hls4ml/data/hept_simplified_out.dat
Part: xcvu13p-flga2577-2-e
ProjectName: myproject
PytorchModel: !!python/object:__main__.SimplifiedHEPTModel
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - - - hept
      - !!python/object:__main__.SimplifiedHEPT
        _backward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _buffers: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
        - []
        _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
        - []
        _is_full_backward_hook: null
        _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _modules: !!python/object/apply:collections.OrderedDict
        - []
        _non_persistent_buffers_set: !!set {}
        _parameters: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_hooks: !!python/object/apply:collections.OrderedDict
        - []
        _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
        - []
        batch_size: 5
        dim_per_head: 7
        n_heads: 3
        seq_len: 2
        training: false
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  training: false
Stamp: b047580a
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
