// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_merge_sort_ap_fixed_16_6_5_3_0_config5_Pipeline_VITIS_LOOP_161_511 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        temp_298,
        temp_297,
        temp_296,
        temp_295,
        temp_294,
        temp_293,
        temp_292,
        temp_291,
        zext_ln161_2,
        k_36,
        mux_case_0413299,
        mux_case_1414303,
        mux_case_2415307,
        mux_case_3416311,
        temp_306_out,
        temp_306_out_ap_vld,
        temp_305_out,
        temp_305_out_ap_vld,
        temp_304_out,
        temp_304_out_ap_vld,
        temp_303_out,
        temp_303_out_ap_vld,
        temp_302_out,
        temp_302_out_ap_vld,
        temp_301_out,
        temp_301_out_ap_vld,
        temp_300_out,
        temp_300_out_ap_vld,
        temp_299_out,
        temp_299_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] temp_298;
input  [31:0] temp_297;
input  [31:0] temp_296;
input  [31:0] temp_295;
input  [31:0] temp_294;
input  [31:0] temp_293;
input  [31:0] temp_292;
input  [31:0] temp_291;
input  [1:0] zext_ln161_2;
input  [31:0] k_36;
input  [31:0] mux_case_0413299;
input  [31:0] mux_case_1414303;
input  [31:0] mux_case_2415307;
input  [31:0] mux_case_3416311;
output  [31:0] temp_306_out;
output   temp_306_out_ap_vld;
output  [31:0] temp_305_out;
output   temp_305_out_ap_vld;
output  [31:0] temp_304_out;
output   temp_304_out_ap_vld;
output  [31:0] temp_303_out;
output   temp_303_out_ap_vld;
output  [31:0] temp_302_out;
output   temp_302_out_ap_vld;
output  [31:0] temp_301_out;
output   temp_301_out_ap_vld;
output  [31:0] temp_300_out;
output   temp_300_out_ap_vld;
output  [31:0] temp_299_out;
output   temp_299_out_ap_vld;

reg ap_idle;
reg temp_306_out_ap_vld;
reg temp_305_out_ap_vld;
reg temp_304_out_ap_vld;
reg temp_303_out_ap_vld;
reg temp_302_out_ap_vld;
reg temp_301_out_ap_vld;
reg temp_300_out_ap_vld;
reg temp_299_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_331_p3;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] k_fu_94;
wire   [31:0] k_6_fu_376_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [2:0] j_fu_98;
wire   [2:0] add_ln163_fu_350_p2;
wire   [2:0] zext_ln161_2_cast_fu_274_p1;
reg   [31:0] temp_fu_102;
wire   [31:0] temp_48_fu_356_p11;
wire   [2:0] trunc_ln147_5_fu_346_p1;
reg   [31:0] temp_41_fu_106;
reg   [31:0] temp_42_fu_110;
reg   [31:0] temp_43_fu_114;
reg   [31:0] temp_44_fu_118;
reg   [31:0] temp_45_fu_122;
reg   [31:0] temp_46_fu_126;
reg   [31:0] temp_47_fu_130;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] temp_48_fu_356_p9;
wire   [1:0] temp_48_fu_356_p10;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_264;
reg    ap_condition_267;
reg    ap_condition_270;
reg    ap_condition_273;
reg    ap_condition_276;
reg    ap_condition_279;
reg    ap_condition_282;
reg    ap_condition_285;
wire   [1:0] temp_48_fu_356_p1;
wire   [1:0] temp_48_fu_356_p3;
wire  signed [1:0] temp_48_fu_356_p5;
wire  signed [1:0] temp_48_fu_356_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 k_fu_94 = 32'd0;
#0 j_fu_98 = 3'd0;
#0 temp_fu_102 = 32'd0;
#0 temp_41_fu_106 = 32'd0;
#0 temp_42_fu_110 = 32'd0;
#0 temp_43_fu_114 = 32'd0;
#0 temp_44_fu_118 = 32'd0;
#0 temp_45_fu_122 = 32'd0;
#0 temp_46_fu_126 = 32'd0;
#0 temp_47_fu_130 = 32'd0;
#0 ap_done_reg = 1'b0;
end

myproject_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U1278(
    .din0(mux_case_0413299),
    .din1(mux_case_1414303),
    .din2(mux_case_2415307),
    .din3(mux_case_3416311),
    .def(temp_48_fu_356_p9),
    .sel(temp_48_fu_356_p10),
    .dout(temp_48_fu_356_p11)
);

myproject_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_98 <= zext_ln161_2_cast_fu_274_p1;
        end else if (((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            j_fu_98 <= add_ln163_fu_350_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_94 <= k_36;
        end else if (((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            k_fu_94 <= k_6_fu_376_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_41_fu_106 <= temp_292;
        end else if ((1'b1 == ap_condition_264)) begin
            temp_41_fu_106 <= temp_48_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_42_fu_110 <= temp_293;
        end else if ((1'b1 == ap_condition_267)) begin
            temp_42_fu_110 <= temp_48_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_43_fu_114 <= temp_294;
        end else if ((1'b1 == ap_condition_270)) begin
            temp_43_fu_114 <= temp_48_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_44_fu_118 <= temp_295;
        end else if ((1'b1 == ap_condition_273)) begin
            temp_44_fu_118 <= temp_48_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_45_fu_122 <= temp_296;
        end else if ((1'b1 == ap_condition_276)) begin
            temp_45_fu_122 <= temp_48_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_46_fu_126 <= temp_297;
        end else if ((1'b1 == ap_condition_279)) begin
            temp_46_fu_126 <= temp_48_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_47_fu_130 <= temp_298;
        end else if ((1'b1 == ap_condition_282)) begin
            temp_47_fu_130 <= temp_48_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_fu_102 <= temp_291;
        end else if ((1'b1 == ap_condition_285)) begin
            temp_fu_102 <= temp_48_fu_356_p11;
        end
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_299_out_ap_vld = 1'b1;
    end else begin
        temp_299_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_300_out_ap_vld = 1'b1;
    end else begin
        temp_300_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_301_out_ap_vld = 1'b1;
    end else begin
        temp_301_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_302_out_ap_vld = 1'b1;
    end else begin
        temp_302_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_303_out_ap_vld = 1'b1;
    end else begin
        temp_303_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_304_out_ap_vld = 1'b1;
    end else begin
        temp_304_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_305_out_ap_vld = 1'b1;
    end else begin
        temp_305_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_306_out_ap_vld = 1'b1;
    end else begin
        temp_306_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln163_fu_350_p2 = (j_fu_98 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_264 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_5_fu_346_p1 == 3'd1));
end

always @ (*) begin
    ap_condition_267 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_5_fu_346_p1 == 3'd2));
end

always @ (*) begin
    ap_condition_270 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_5_fu_346_p1 == 3'd3));
end

always @ (*) begin
    ap_condition_273 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_5_fu_346_p1 == 3'd4));
end

always @ (*) begin
    ap_condition_276 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_5_fu_346_p1 == 3'd5));
end

always @ (*) begin
    ap_condition_279 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_5_fu_346_p1 == 3'd6));
end

always @ (*) begin
    ap_condition_282 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_5_fu_346_p1 == 3'd7));
end

always @ (*) begin
    ap_condition_285 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_5_fu_346_p1 == 3'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign k_6_fu_376_p2 = (k_fu_94 + 32'd1);

assign temp_299_out = temp_fu_102;

assign temp_300_out = temp_41_fu_106;

assign temp_301_out = temp_42_fu_110;

assign temp_302_out = temp_43_fu_114;

assign temp_303_out = temp_44_fu_118;

assign temp_304_out = temp_45_fu_122;

assign temp_305_out = temp_46_fu_126;

assign temp_306_out = temp_47_fu_130;

assign temp_48_fu_356_p10 = j_fu_98[1:0];

assign temp_48_fu_356_p9 = 'bx;

assign tmp_fu_331_p3 = j_fu_98[32'd2];

assign trunc_ln147_5_fu_346_p1 = k_fu_94[2:0];

assign zext_ln161_2_cast_fu_274_p1 = zext_ln161_2;

endmodule //myproject_merge_sort_ap_fixed_16_6_5_3_0_config5_Pipeline_VITIS_LOOP_161_511
