# ==============================================================
# Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2023.2 (64-bit)
# Tool Version Limit: 2023.10
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
# 
# ==============================================================
proc sc_sim_check {ret err logfile} {
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] start...";
	}
    set errfile "err.log"
    if {[file exists $errfile] && [file size $errfile] != 0} {
        set fl [open $errfile r]
        while {[gets $fl line] >= 0} {
            if {[string first "AESL_mErrNo = " $line] == 0} {
                set mismatch_num [string range $line [string length "AESL_mErrNo = "] end]
                if {$mismatch_num != 0} {
                    ::AP::printMsg ERR COSIM 403 COSIM_403_986 ${mismatch_num}
                    break
                }
            }
        }
    }
    if {$ret || $err != ""} {
        if { [lindex $::errorCode 0] eq "CHILDSTATUS"} {
            set status [lindex $::errorCode 2]
            if {$status != ""} {
                ::AP::printMsg ERR COSIM 404 COSIM_404_987 $status
            } else {
                ::AP::printMsg ERR COSIM 405 COSIM_405_988
            }
        } else {
            ::AP::printMsg ERR COSIM 405 COSIM_405_989
        }
    }
    if {[file exists $logfile]} {
        set cmdret [catch {eval exec "grep \"Error:\" $logfile"} err]
        file delete -force $logfile
        if {$cmdret == 0} {
            ::AP::printMsg ERR COSIM 405 COSIM_405_990
        }
    }
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] finish...";
	}
}

proc rtl_sim_check {} {
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] start...";
	}
    set errfile "err.log"
    if {[file exists $errfile] && [file size $errfile] != 0} {
        set fl [open $errfile r]
        set unmatch_num 0
        while {[gets $fl line] >= 0} {
            if {[string first "unmatched" $line] != -1} {
                set unmatch_num [expr $unmatch_num + 1]
            }
        }
        if {$unmatch_num != 0} {
            ::AP::printMsg ERR COSIM 406 COSIM_406_991 ${unmatch_num}
        }
    }
    if {[file exists ".aesl_error"]} {
        set errfl [open ".aesl_error" r]
        gets $errfl line
        if {$line != 0} {
            ::AP::printMsg ERR COSIM 407 COSIM_407_992 $line
        }
    }
    if {[file exists ".exit.err"]} {
        ::AP::printMsg ERR COSIM 405 COSIM_405_993
    }
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] finish...";
	}
}

proc check_tvin_file {} {
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] start...";
	}
    set rtlfilelist {
         "c.myproject.autotvin_query_0.dat"
         "c.myproject.autotvin_query_1.dat"
         "c.myproject.autotvin_query_2.dat"
         "c.myproject.autotvin_query_3.dat"
         "c.myproject.autotvin_query_4.dat"
         "c.myproject.autotvin_query_5.dat"
         "c.myproject.autotvin_query_6.dat"
         "c.myproject.autotvin_query_7.dat"
         "c.myproject.autotvin_query_8.dat"
         "c.myproject.autotvin_query_9.dat"
         "c.myproject.autotvin_query_10.dat"
         "c.myproject.autotvin_query_11.dat"
         "c.myproject.autotvin_query_12.dat"
         "c.myproject.autotvin_query_13.dat"
         "c.myproject.autotvin_query_14.dat"
         "c.myproject.autotvin_query_15.dat"
         "c.myproject.autotvin_query_16.dat"
         "c.myproject.autotvin_query_17.dat"
         "c.myproject.autotvin_query_18.dat"
         "c.myproject.autotvin_query_19.dat"
         "c.myproject.autotvin_query_20.dat"
         "c.myproject.autotvin_query_21.dat"
         "c.myproject.autotvin_query_22.dat"
         "c.myproject.autotvin_query_23.dat"
         "c.myproject.autotvin_query_24.dat"
         "c.myproject.autotvin_query_25.dat"
         "c.myproject.autotvin_query_26.dat"
         "c.myproject.autotvin_query_27.dat"
         "c.myproject.autotvin_query_28.dat"
         "c.myproject.autotvin_query_29.dat"
         "c.myproject.autotvin_query_30.dat"
         "c.myproject.autotvin_query_31.dat"
         "c.myproject.autotvin_query_32.dat"
         "c.myproject.autotvin_query_33.dat"
         "c.myproject.autotvin_query_34.dat"
         "c.myproject.autotvin_query_35.dat"
         "c.myproject.autotvin_query_36.dat"
         "c.myproject.autotvin_query_37.dat"
         "c.myproject.autotvin_query_38.dat"
         "c.myproject.autotvin_query_39.dat"
         "c.myproject.autotvin_query_40.dat"
         "c.myproject.autotvin_query_41.dat"
         "c.myproject.autotvin_query_42.dat"
         "c.myproject.autotvin_query_43.dat"
         "c.myproject.autotvin_query_44.dat"
         "c.myproject.autotvin_query_45.dat"
         "c.myproject.autotvin_query_46.dat"
         "c.myproject.autotvin_query_47.dat"
         "c.myproject.autotvin_query_48.dat"
         "c.myproject.autotvin_query_49.dat"
         "c.myproject.autotvin_query_50.dat"
         "c.myproject.autotvin_query_51.dat"
         "c.myproject.autotvin_query_52.dat"
         "c.myproject.autotvin_query_53.dat"
         "c.myproject.autotvin_query_54.dat"
         "c.myproject.autotvin_query_55.dat"
         "c.myproject.autotvin_query_56.dat"
         "c.myproject.autotvin_query_57.dat"
         "c.myproject.autotvin_query_58.dat"
         "c.myproject.autotvin_query_59.dat"
         "c.myproject.autotvin_query_60.dat"
         "c.myproject.autotvin_query_61.dat"
         "c.myproject.autotvin_query_62.dat"
         "c.myproject.autotvin_query_63.dat"
         "c.myproject.autotvin_query_64.dat"
         "c.myproject.autotvin_query_65.dat"
         "c.myproject.autotvin_query_66.dat"
         "c.myproject.autotvin_query_67.dat"
         "c.myproject.autotvin_query_68.dat"
         "c.myproject.autotvin_query_69.dat"
         "c.myproject.autotvin_query_70.dat"
         "c.myproject.autotvin_query_71.dat"
         "c.myproject.autotvin_query_72.dat"
         "c.myproject.autotvin_query_73.dat"
         "c.myproject.autotvin_query_74.dat"
         "c.myproject.autotvin_query_75.dat"
         "c.myproject.autotvin_query_76.dat"
         "c.myproject.autotvin_query_77.dat"
         "c.myproject.autotvin_query_78.dat"
         "c.myproject.autotvin_query_79.dat"
         "c.myproject.autotvin_query_80.dat"
         "c.myproject.autotvin_query_81.dat"
         "c.myproject.autotvin_query_82.dat"
         "c.myproject.autotvin_query_83.dat"
         "c.myproject.autotvin_query_84.dat"
         "c.myproject.autotvin_query_85.dat"
         "c.myproject.autotvin_query_86.dat"
         "c.myproject.autotvin_query_87.dat"
         "c.myproject.autotvin_query_88.dat"
         "c.myproject.autotvin_query_89.dat"
         "c.myproject.autotvin_query_90.dat"
         "c.myproject.autotvin_query_91.dat"
         "c.myproject.autotvin_query_92.dat"
         "c.myproject.autotvin_query_93.dat"
         "c.myproject.autotvin_query_94.dat"
         "c.myproject.autotvin_query_95.dat"
         "c.myproject.autotvin_query_96.dat"
         "c.myproject.autotvin_query_97.dat"
         "c.myproject.autotvin_query_98.dat"
         "c.myproject.autotvin_query_99.dat"
         "c.myproject.autotvin_query_100.dat"
         "c.myproject.autotvin_query_101.dat"
         "c.myproject.autotvin_query_102.dat"
         "c.myproject.autotvin_query_103.dat"
         "c.myproject.autotvin_query_104.dat"
         "c.myproject.autotvin_query_105.dat"
         "c.myproject.autotvin_query_106.dat"
         "c.myproject.autotvin_query_107.dat"
         "c.myproject.autotvin_query_108.dat"
         "c.myproject.autotvin_query_109.dat"
         "c.myproject.autotvin_query_110.dat"
         "c.myproject.autotvin_query_111.dat"
         "c.myproject.autotvin_query_112.dat"
         "c.myproject.autotvin_query_113.dat"
         "c.myproject.autotvin_query_114.dat"
         "c.myproject.autotvin_query_115.dat"
         "c.myproject.autotvin_query_116.dat"
         "c.myproject.autotvin_query_117.dat"
         "c.myproject.autotvin_query_118.dat"
         "c.myproject.autotvin_query_119.dat"
         "c.myproject.autotvin_query_120.dat"
         "c.myproject.autotvin_query_121.dat"
         "c.myproject.autotvin_query_122.dat"
         "c.myproject.autotvin_query_123.dat"
         "c.myproject.autotvin_query_124.dat"
         "c.myproject.autotvin_query_125.dat"
         "c.myproject.autotvin_query_126.dat"
         "c.myproject.autotvin_query_127.dat"
         "c.myproject.autotvin_query_128.dat"
         "c.myproject.autotvin_query_129.dat"
         "c.myproject.autotvin_query_130.dat"
         "c.myproject.autotvin_query_131.dat"
         "c.myproject.autotvin_query_132.dat"
         "c.myproject.autotvin_query_133.dat"
         "c.myproject.autotvin_query_134.dat"
         "c.myproject.autotvin_query_135.dat"
         "c.myproject.autotvin_query_136.dat"
         "c.myproject.autotvin_query_137.dat"
         "c.myproject.autotvin_query_138.dat"
         "c.myproject.autotvin_query_139.dat"
         "c.myproject.autotvin_query_140.dat"
         "c.myproject.autotvin_query_141.dat"
         "c.myproject.autotvin_query_142.dat"
         "c.myproject.autotvin_query_143.dat"
         "c.myproject.autotvin_query_144.dat"
         "c.myproject.autotvin_query_145.dat"
         "c.myproject.autotvin_query_146.dat"
         "c.myproject.autotvin_query_147.dat"
         "c.myproject.autotvin_query_148.dat"
         "c.myproject.autotvin_query_149.dat"
         "c.myproject.autotvin_query_150.dat"
         "c.myproject.autotvin_query_151.dat"
         "c.myproject.autotvin_query_152.dat"
         "c.myproject.autotvin_query_153.dat"
         "c.myproject.autotvin_query_154.dat"
         "c.myproject.autotvin_query_155.dat"
         "c.myproject.autotvin_query_156.dat"
         "c.myproject.autotvin_query_157.dat"
         "c.myproject.autotvin_query_158.dat"
         "c.myproject.autotvin_query_159.dat"
         "c.myproject.autotvin_query_160.dat"
         "c.myproject.autotvin_query_161.dat"
         "c.myproject.autotvin_query_162.dat"
         "c.myproject.autotvin_query_163.dat"
         "c.myproject.autotvin_query_164.dat"
         "c.myproject.autotvin_query_165.dat"
         "c.myproject.autotvin_query_166.dat"
         "c.myproject.autotvin_query_167.dat"
         "c.myproject.autotvin_query_168.dat"
         "c.myproject.autotvin_query_169.dat"
         "c.myproject.autotvin_query_170.dat"
         "c.myproject.autotvin_query_171.dat"
         "c.myproject.autotvin_query_172.dat"
         "c.myproject.autotvin_query_173.dat"
         "c.myproject.autotvin_query_174.dat"
         "c.myproject.autotvin_query_175.dat"
         "c.myproject.autotvin_query_176.dat"
         "c.myproject.autotvin_query_177.dat"
         "c.myproject.autotvin_query_178.dat"
         "c.myproject.autotvin_query_179.dat"
         "c.myproject.autotvin_query_180.dat"
         "c.myproject.autotvin_query_181.dat"
         "c.myproject.autotvin_query_182.dat"
         "c.myproject.autotvin_query_183.dat"
         "c.myproject.autotvin_query_184.dat"
         "c.myproject.autotvin_query_185.dat"
         "c.myproject.autotvin_query_186.dat"
         "c.myproject.autotvin_query_187.dat"
         "c.myproject.autotvin_query_188.dat"
         "c.myproject.autotvin_query_189.dat"
         "c.myproject.autotvin_query_190.dat"
         "c.myproject.autotvin_query_191.dat"
         "c.myproject.autotvin_query_192.dat"
         "c.myproject.autotvin_query_193.dat"
         "c.myproject.autotvin_query_194.dat"
         "c.myproject.autotvin_query_195.dat"
         "c.myproject.autotvin_query_196.dat"
         "c.myproject.autotvin_query_197.dat"
         "c.myproject.autotvin_query_198.dat"
         "c.myproject.autotvin_query_199.dat"
         "c.myproject.autotvin_query_200.dat"
         "c.myproject.autotvin_query_201.dat"
         "c.myproject.autotvin_query_202.dat"
         "c.myproject.autotvin_query_203.dat"
         "c.myproject.autotvin_query_204.dat"
         "c.myproject.autotvin_query_205.dat"
         "c.myproject.autotvin_query_206.dat"
         "c.myproject.autotvin_query_207.dat"
         "c.myproject.autotvin_query_208.dat"
         "c.myproject.autotvin_query_209.dat"
         "c.myproject.autotvin_key_0.dat"
         "c.myproject.autotvin_key_1.dat"
         "c.myproject.autotvin_key_2.dat"
         "c.myproject.autotvin_key_3.dat"
         "c.myproject.autotvin_key_4.dat"
         "c.myproject.autotvin_key_5.dat"
         "c.myproject.autotvin_key_6.dat"
         "c.myproject.autotvin_key_7.dat"
         "c.myproject.autotvin_key_8.dat"
         "c.myproject.autotvin_key_9.dat"
         "c.myproject.autotvin_key_10.dat"
         "c.myproject.autotvin_key_11.dat"
         "c.myproject.autotvin_key_12.dat"
         "c.myproject.autotvin_key_13.dat"
         "c.myproject.autotvin_key_14.dat"
         "c.myproject.autotvin_key_15.dat"
         "c.myproject.autotvin_key_16.dat"
         "c.myproject.autotvin_key_17.dat"
         "c.myproject.autotvin_key_18.dat"
         "c.myproject.autotvin_key_19.dat"
         "c.myproject.autotvin_key_20.dat"
         "c.myproject.autotvin_key_21.dat"
         "c.myproject.autotvin_key_22.dat"
         "c.myproject.autotvin_key_23.dat"
         "c.myproject.autotvin_key_24.dat"
         "c.myproject.autotvin_key_25.dat"
         "c.myproject.autotvin_key_26.dat"
         "c.myproject.autotvin_key_27.dat"
         "c.myproject.autotvin_key_28.dat"
         "c.myproject.autotvin_key_29.dat"
         "c.myproject.autotvin_key_30.dat"
         "c.myproject.autotvin_key_31.dat"
         "c.myproject.autotvin_key_32.dat"
         "c.myproject.autotvin_key_33.dat"
         "c.myproject.autotvin_key_34.dat"
         "c.myproject.autotvin_key_35.dat"
         "c.myproject.autotvin_key_36.dat"
         "c.myproject.autotvin_key_37.dat"
         "c.myproject.autotvin_key_38.dat"
         "c.myproject.autotvin_key_39.dat"
         "c.myproject.autotvin_key_40.dat"
         "c.myproject.autotvin_key_41.dat"
         "c.myproject.autotvin_key_42.dat"
         "c.myproject.autotvin_key_43.dat"
         "c.myproject.autotvin_key_44.dat"
         "c.myproject.autotvin_key_45.dat"
         "c.myproject.autotvin_key_46.dat"
         "c.myproject.autotvin_key_47.dat"
         "c.myproject.autotvin_key_48.dat"
         "c.myproject.autotvin_key_49.dat"
         "c.myproject.autotvin_key_50.dat"
         "c.myproject.autotvin_key_51.dat"
         "c.myproject.autotvin_key_52.dat"
         "c.myproject.autotvin_key_53.dat"
         "c.myproject.autotvin_key_54.dat"
         "c.myproject.autotvin_key_55.dat"
         "c.myproject.autotvin_key_56.dat"
         "c.myproject.autotvin_key_57.dat"
         "c.myproject.autotvin_key_58.dat"
         "c.myproject.autotvin_key_59.dat"
         "c.myproject.autotvin_key_60.dat"
         "c.myproject.autotvin_key_61.dat"
         "c.myproject.autotvin_key_62.dat"
         "c.myproject.autotvin_key_63.dat"
         "c.myproject.autotvin_key_64.dat"
         "c.myproject.autotvin_key_65.dat"
         "c.myproject.autotvin_key_66.dat"
         "c.myproject.autotvin_key_67.dat"
         "c.myproject.autotvin_key_68.dat"
         "c.myproject.autotvin_key_69.dat"
         "c.myproject.autotvin_key_70.dat"
         "c.myproject.autotvin_key_71.dat"
         "c.myproject.autotvin_key_72.dat"
         "c.myproject.autotvin_key_73.dat"
         "c.myproject.autotvin_key_74.dat"
         "c.myproject.autotvin_key_75.dat"
         "c.myproject.autotvin_key_76.dat"
         "c.myproject.autotvin_key_77.dat"
         "c.myproject.autotvin_key_78.dat"
         "c.myproject.autotvin_key_79.dat"
         "c.myproject.autotvin_key_80.dat"
         "c.myproject.autotvin_key_81.dat"
         "c.myproject.autotvin_key_82.dat"
         "c.myproject.autotvin_key_83.dat"
         "c.myproject.autotvin_key_84.dat"
         "c.myproject.autotvin_key_85.dat"
         "c.myproject.autotvin_key_86.dat"
         "c.myproject.autotvin_key_87.dat"
         "c.myproject.autotvin_key_88.dat"
         "c.myproject.autotvin_key_89.dat"
         "c.myproject.autotvin_key_90.dat"
         "c.myproject.autotvin_key_91.dat"
         "c.myproject.autotvin_key_92.dat"
         "c.myproject.autotvin_key_93.dat"
         "c.myproject.autotvin_key_94.dat"
         "c.myproject.autotvin_key_95.dat"
         "c.myproject.autotvin_key_96.dat"
         "c.myproject.autotvin_key_97.dat"
         "c.myproject.autotvin_key_98.dat"
         "c.myproject.autotvin_key_99.dat"
         "c.myproject.autotvin_key_100.dat"
         "c.myproject.autotvin_key_101.dat"
         "c.myproject.autotvin_key_102.dat"
         "c.myproject.autotvin_key_103.dat"
         "c.myproject.autotvin_key_104.dat"
         "c.myproject.autotvin_key_105.dat"
         "c.myproject.autotvin_key_106.dat"
         "c.myproject.autotvin_key_107.dat"
         "c.myproject.autotvin_key_108.dat"
         "c.myproject.autotvin_key_109.dat"
         "c.myproject.autotvin_key_110.dat"
         "c.myproject.autotvin_key_111.dat"
         "c.myproject.autotvin_key_112.dat"
         "c.myproject.autotvin_key_113.dat"
         "c.myproject.autotvin_key_114.dat"
         "c.myproject.autotvin_key_115.dat"
         "c.myproject.autotvin_key_116.dat"
         "c.myproject.autotvin_key_117.dat"
         "c.myproject.autotvin_key_118.dat"
         "c.myproject.autotvin_key_119.dat"
         "c.myproject.autotvin_key_120.dat"
         "c.myproject.autotvin_key_121.dat"
         "c.myproject.autotvin_key_122.dat"
         "c.myproject.autotvin_key_123.dat"
         "c.myproject.autotvin_key_124.dat"
         "c.myproject.autotvin_key_125.dat"
         "c.myproject.autotvin_key_126.dat"
         "c.myproject.autotvin_key_127.dat"
         "c.myproject.autotvin_key_128.dat"
         "c.myproject.autotvin_key_129.dat"
         "c.myproject.autotvin_key_130.dat"
         "c.myproject.autotvin_key_131.dat"
         "c.myproject.autotvin_key_132.dat"
         "c.myproject.autotvin_key_133.dat"
         "c.myproject.autotvin_key_134.dat"
         "c.myproject.autotvin_key_135.dat"
         "c.myproject.autotvin_key_136.dat"
         "c.myproject.autotvin_key_137.dat"
         "c.myproject.autotvin_key_138.dat"
         "c.myproject.autotvin_key_139.dat"
         "c.myproject.autotvin_key_140.dat"
         "c.myproject.autotvin_key_141.dat"
         "c.myproject.autotvin_key_142.dat"
         "c.myproject.autotvin_key_143.dat"
         "c.myproject.autotvin_key_144.dat"
         "c.myproject.autotvin_key_145.dat"
         "c.myproject.autotvin_key_146.dat"
         "c.myproject.autotvin_key_147.dat"
         "c.myproject.autotvin_key_148.dat"
         "c.myproject.autotvin_key_149.dat"
         "c.myproject.autotvin_key_150.dat"
         "c.myproject.autotvin_key_151.dat"
         "c.myproject.autotvin_key_152.dat"
         "c.myproject.autotvin_key_153.dat"
         "c.myproject.autotvin_key_154.dat"
         "c.myproject.autotvin_key_155.dat"
         "c.myproject.autotvin_key_156.dat"
         "c.myproject.autotvin_key_157.dat"
         "c.myproject.autotvin_key_158.dat"
         "c.myproject.autotvin_key_159.dat"
         "c.myproject.autotvin_key_160.dat"
         "c.myproject.autotvin_key_161.dat"
         "c.myproject.autotvin_key_162.dat"
         "c.myproject.autotvin_key_163.dat"
         "c.myproject.autotvin_key_164.dat"
         "c.myproject.autotvin_key_165.dat"
         "c.myproject.autotvin_key_166.dat"
         "c.myproject.autotvin_key_167.dat"
         "c.myproject.autotvin_key_168.dat"
         "c.myproject.autotvin_key_169.dat"
         "c.myproject.autotvin_key_170.dat"
         "c.myproject.autotvin_key_171.dat"
         "c.myproject.autotvin_key_172.dat"
         "c.myproject.autotvin_key_173.dat"
         "c.myproject.autotvin_key_174.dat"
         "c.myproject.autotvin_key_175.dat"
         "c.myproject.autotvin_key_176.dat"
         "c.myproject.autotvin_key_177.dat"
         "c.myproject.autotvin_key_178.dat"
         "c.myproject.autotvin_key_179.dat"
         "c.myproject.autotvin_key_180.dat"
         "c.myproject.autotvin_key_181.dat"
         "c.myproject.autotvin_key_182.dat"
         "c.myproject.autotvin_key_183.dat"
         "c.myproject.autotvin_key_184.dat"
         "c.myproject.autotvin_key_185.dat"
         "c.myproject.autotvin_key_186.dat"
         "c.myproject.autotvin_key_187.dat"
         "c.myproject.autotvin_key_188.dat"
         "c.myproject.autotvin_key_189.dat"
         "c.myproject.autotvin_key_190.dat"
         "c.myproject.autotvin_key_191.dat"
         "c.myproject.autotvin_key_192.dat"
         "c.myproject.autotvin_key_193.dat"
         "c.myproject.autotvin_key_194.dat"
         "c.myproject.autotvin_key_195.dat"
         "c.myproject.autotvin_key_196.dat"
         "c.myproject.autotvin_key_197.dat"
         "c.myproject.autotvin_key_198.dat"
         "c.myproject.autotvin_key_199.dat"
         "c.myproject.autotvin_key_200.dat"
         "c.myproject.autotvin_key_201.dat"
         "c.myproject.autotvin_key_202.dat"
         "c.myproject.autotvin_key_203.dat"
         "c.myproject.autotvin_key_204.dat"
         "c.myproject.autotvin_key_205.dat"
         "c.myproject.autotvin_key_206.dat"
         "c.myproject.autotvin_key_207.dat"
         "c.myproject.autotvin_key_208.dat"
         "c.myproject.autotvin_key_209.dat"
    }
    foreach rtlfile $rtlfilelist {
        if {[file isfile $rtlfile]} {
        } else {
            ::AP::printMsg ERR COSIM 320 COSIM_320_994
            return 1
        }
    }
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] finish...";
	}
    return 0
}

proc check_tvout_file {} {
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] start...";
	}
    set rtlfilelist {
         "rtl.myproject.autotvout_layer3_out_0.dat"
         "rtl.myproject.autotvout_layer3_out_1.dat"
         "rtl.myproject.autotvout_layer3_out_2.dat"
         "rtl.myproject.autotvout_layer3_out_3.dat"
         "rtl.myproject.autotvout_layer3_out_4.dat"
         "rtl.myproject.autotvout_layer3_out_5.dat"
         "rtl.myproject.autotvout_layer3_out_6.dat"
         "rtl.myproject.autotvout_layer3_out_7.dat"
         "rtl.myproject.autotvout_layer3_out_8.dat"
         "rtl.myproject.autotvout_layer3_out_9.dat"
         "rtl.myproject.autotvout_layer3_out_10.dat"
         "rtl.myproject.autotvout_layer3_out_11.dat"
         "rtl.myproject.autotvout_layer3_out_12.dat"
         "rtl.myproject.autotvout_layer3_out_13.dat"
         "rtl.myproject.autotvout_layer3_out_14.dat"
         "rtl.myproject.autotvout_layer3_out_15.dat"
         "rtl.myproject.autotvout_layer3_out_16.dat"
         "rtl.myproject.autotvout_layer3_out_17.dat"
         "rtl.myproject.autotvout_layer3_out_18.dat"
         "rtl.myproject.autotvout_layer3_out_19.dat"
         "rtl.myproject.autotvout_layer3_out_20.dat"
         "rtl.myproject.autotvout_layer3_out_21.dat"
         "rtl.myproject.autotvout_layer3_out_22.dat"
         "rtl.myproject.autotvout_layer3_out_23.dat"
         "rtl.myproject.autotvout_layer3_out_24.dat"
         "rtl.myproject.autotvout_layer3_out_25.dat"
         "rtl.myproject.autotvout_layer3_out_26.dat"
         "rtl.myproject.autotvout_layer3_out_27.dat"
         "rtl.myproject.autotvout_layer3_out_28.dat"
         "rtl.myproject.autotvout_layer3_out_29.dat"
         "rtl.myproject.autotvout_layer3_out_30.dat"
         "rtl.myproject.autotvout_layer3_out_31.dat"
         "rtl.myproject.autotvout_layer3_out_32.dat"
         "rtl.myproject.autotvout_layer3_out_33.dat"
         "rtl.myproject.autotvout_layer3_out_34.dat"
         "rtl.myproject.autotvout_layer3_out_35.dat"
         "rtl.myproject.autotvout_layer3_out_36.dat"
         "rtl.myproject.autotvout_layer3_out_37.dat"
         "rtl.myproject.autotvout_layer3_out_38.dat"
         "rtl.myproject.autotvout_layer3_out_39.dat"
         "rtl.myproject.autotvout_layer3_out_40.dat"
         "rtl.myproject.autotvout_layer3_out_41.dat"
         "rtl.myproject.autotvout_layer3_out_42.dat"
         "rtl.myproject.autotvout_layer3_out_43.dat"
         "rtl.myproject.autotvout_layer3_out_44.dat"
         "rtl.myproject.autotvout_layer3_out_45.dat"
         "rtl.myproject.autotvout_layer3_out_46.dat"
         "rtl.myproject.autotvout_layer3_out_47.dat"
         "rtl.myproject.autotvout_layer3_out_48.dat"
         "rtl.myproject.autotvout_layer3_out_49.dat"
         "rtl.myproject.autotvout_layer3_out_50.dat"
         "rtl.myproject.autotvout_layer3_out_51.dat"
         "rtl.myproject.autotvout_layer3_out_52.dat"
         "rtl.myproject.autotvout_layer3_out_53.dat"
         "rtl.myproject.autotvout_layer3_out_54.dat"
         "rtl.myproject.autotvout_layer3_out_55.dat"
         "rtl.myproject.autotvout_layer3_out_56.dat"
         "rtl.myproject.autotvout_layer3_out_57.dat"
         "rtl.myproject.autotvout_layer3_out_58.dat"
         "rtl.myproject.autotvout_layer3_out_59.dat"
    }
    foreach rtlfile $rtlfilelist {
        if {[file isfile $rtlfile]} {
        } else {
            ::AP::printMsg ERR COSIM 303 COSIM_303_996
            return 1
        }
    }
	if {$::AESL_AUTOSIM::gDebug == 1} {
		puts stdout "[debug_prompt arg check_sim.tcl] finish...";
	}
    return 0
}
