// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_merge_sort_ap_fixed_16_6_5_3_0_config5_Pipeline_VITIS_LOOP_161_52 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        temp_85,
        temp_84,
        temp_83,
        temp_82,
        temp_81,
        temp_80,
        temp_79,
        temp_78,
        zext_ln161,
        k_9,
        mux_case_07711,
        mux_case_17815,
        mux_case_27919,
        mux_case_38023,
        temp_102_out,
        temp_102_out_ap_vld,
        temp_101_out,
        temp_101_out_ap_vld,
        temp_100_out,
        temp_100_out_ap_vld,
        temp_99_out,
        temp_99_out_ap_vld,
        temp_98_out,
        temp_98_out_ap_vld,
        temp_97_out,
        temp_97_out_ap_vld,
        temp_96_out,
        temp_96_out_ap_vld,
        temp_95_out,
        temp_95_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] temp_85;
input  [31:0] temp_84;
input  [31:0] temp_83;
input  [31:0] temp_82;
input  [31:0] temp_81;
input  [31:0] temp_80;
input  [31:0] temp_79;
input  [31:0] temp_78;
input  [1:0] zext_ln161;
input  [31:0] k_9;
input  [31:0] mux_case_07711;
input  [31:0] mux_case_17815;
input  [31:0] mux_case_27919;
input  [31:0] mux_case_38023;
output  [31:0] temp_102_out;
output   temp_102_out_ap_vld;
output  [31:0] temp_101_out;
output   temp_101_out_ap_vld;
output  [31:0] temp_100_out;
output   temp_100_out_ap_vld;
output  [31:0] temp_99_out;
output   temp_99_out_ap_vld;
output  [31:0] temp_98_out;
output   temp_98_out_ap_vld;
output  [31:0] temp_97_out;
output   temp_97_out_ap_vld;
output  [31:0] temp_96_out;
output   temp_96_out_ap_vld;
output  [31:0] temp_95_out;
output   temp_95_out_ap_vld;

reg ap_idle;
reg temp_102_out_ap_vld;
reg temp_101_out_ap_vld;
reg temp_100_out_ap_vld;
reg temp_99_out_ap_vld;
reg temp_98_out_ap_vld;
reg temp_97_out_ap_vld;
reg temp_96_out_ap_vld;
reg temp_95_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_331_p3;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] k_fu_94;
wire   [31:0] k_3_fu_376_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [2:0] j_fu_98;
wire   [2:0] add_ln163_fu_350_p2;
wire   [2:0] zext_ln161_cast_fu_274_p1;
reg   [31:0] temp_fu_102;
wire   [31:0] temp_24_fu_356_p11;
wire   [2:0] trunc_ln147_2_fu_346_p1;
reg   [31:0] temp_17_fu_106;
reg   [31:0] temp_18_fu_110;
reg   [31:0] temp_19_fu_114;
reg   [31:0] temp_20_fu_118;
reg   [31:0] temp_21_fu_122;
reg   [31:0] temp_22_fu_126;
reg   [31:0] temp_23_fu_130;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] temp_24_fu_356_p9;
wire   [1:0] temp_24_fu_356_p10;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_264;
reg    ap_condition_267;
reg    ap_condition_270;
reg    ap_condition_273;
reg    ap_condition_276;
reg    ap_condition_279;
reg    ap_condition_282;
reg    ap_condition_285;
wire   [1:0] temp_24_fu_356_p1;
wire   [1:0] temp_24_fu_356_p3;
wire  signed [1:0] temp_24_fu_356_p5;
wire  signed [1:0] temp_24_fu_356_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 k_fu_94 = 32'd0;
#0 j_fu_98 = 3'd0;
#0 temp_fu_102 = 32'd0;
#0 temp_17_fu_106 = 32'd0;
#0 temp_18_fu_110 = 32'd0;
#0 temp_19_fu_114 = 32'd0;
#0 temp_20_fu_118 = 32'd0;
#0 temp_21_fu_122 = 32'd0;
#0 temp_22_fu_126 = 32'd0;
#0 temp_23_fu_130 = 32'd0;
#0 ap_done_reg = 1'b0;
end

myproject_sparsemux_9_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_9_2_32_1_1_U873(
    .din0(mux_case_07711),
    .din1(mux_case_17815),
    .din2(mux_case_27919),
    .din3(mux_case_38023),
    .def(temp_24_fu_356_p9),
    .sel(temp_24_fu_356_p10),
    .dout(temp_24_fu_356_p11)
);

myproject_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_98 <= zext_ln161_cast_fu_274_p1;
        end else if (((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            j_fu_98 <= add_ln163_fu_350_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_94 <= k_9;
        end else if (((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            k_fu_94 <= k_3_fu_376_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_17_fu_106 <= temp_79;
        end else if ((1'b1 == ap_condition_264)) begin
            temp_17_fu_106 <= temp_24_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_18_fu_110 <= temp_80;
        end else if ((1'b1 == ap_condition_267)) begin
            temp_18_fu_110 <= temp_24_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_19_fu_114 <= temp_81;
        end else if ((1'b1 == ap_condition_270)) begin
            temp_19_fu_114 <= temp_24_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_20_fu_118 <= temp_82;
        end else if ((1'b1 == ap_condition_273)) begin
            temp_20_fu_118 <= temp_24_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_21_fu_122 <= temp_83;
        end else if ((1'b1 == ap_condition_276)) begin
            temp_21_fu_122 <= temp_24_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_22_fu_126 <= temp_84;
        end else if ((1'b1 == ap_condition_279)) begin
            temp_22_fu_126 <= temp_24_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_23_fu_130 <= temp_85;
        end else if ((1'b1 == ap_condition_282)) begin
            temp_23_fu_130 <= temp_24_fu_356_p11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            temp_fu_102 <= temp_78;
        end else if ((1'b1 == ap_condition_285)) begin
            temp_fu_102 <= temp_24_fu_356_p11;
        end
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_100_out_ap_vld = 1'b1;
    end else begin
        temp_100_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_101_out_ap_vld = 1'b1;
    end else begin
        temp_101_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_102_out_ap_vld = 1'b1;
    end else begin
        temp_102_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_95_out_ap_vld = 1'b1;
    end else begin
        temp_95_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_96_out_ap_vld = 1'b1;
    end else begin
        temp_96_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_97_out_ap_vld = 1'b1;
    end else begin
        temp_97_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_98_out_ap_vld = 1'b1;
    end else begin
        temp_98_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_331_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        temp_99_out_ap_vld = 1'b1;
    end else begin
        temp_99_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln163_fu_350_p2 = (j_fu_98 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_264 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_2_fu_346_p1 == 3'd1));
end

always @ (*) begin
    ap_condition_267 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_2_fu_346_p1 == 3'd2));
end

always @ (*) begin
    ap_condition_270 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_2_fu_346_p1 == 3'd3));
end

always @ (*) begin
    ap_condition_273 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_2_fu_346_p1 == 3'd4));
end

always @ (*) begin
    ap_condition_276 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_2_fu_346_p1 == 3'd5));
end

always @ (*) begin
    ap_condition_279 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_2_fu_346_p1 == 3'd6));
end

always @ (*) begin
    ap_condition_282 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_2_fu_346_p1 == 3'd7));
end

always @ (*) begin
    ap_condition_285 = ((tmp_fu_331_p3 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln147_2_fu_346_p1 == 3'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign k_3_fu_376_p2 = (k_fu_94 + 32'd1);

assign temp_100_out = temp_21_fu_122;

assign temp_101_out = temp_22_fu_126;

assign temp_102_out = temp_23_fu_130;

assign temp_24_fu_356_p10 = j_fu_98[1:0];

assign temp_24_fu_356_p9 = 'bx;

assign temp_95_out = temp_fu_102;

assign temp_96_out = temp_17_fu_106;

assign temp_97_out = temp_18_fu_110;

assign temp_98_out = temp_19_fu_114;

assign temp_99_out = temp_20_fu_118;

assign tmp_fu_331_p3 = j_fu_98[32'd2];

assign trunc_ln147_2_fu_346_p1 = k_fu_94[2:0];

assign zext_ln161_cast_fu_274_p1 = zext_ln161;

endmodule //myproject_merge_sort_ap_fixed_16_6_5_3_0_config5_Pipeline_VITIS_LOOP_161_52
